import time
print('Kadi tu es Gali de hi')
time.sleep(1)
print('Agle morr te milda si')
time.sleep(1)
print('Tainu khabar si saari ke')
time.sleep(1)
print('Haal jo mere dil da si')
time.sleep(1)
print('Tu bhul gaya saariyan oh gallan')
time.sleep(1)
print('Te mai na bhulli ve sajna')
time.sleep(1)
print('Ke aj mainu vekh k vi hath te')
time.sleep(1)
print('Teri chaah dulli na sajna')
time.sleep(1)
print('Vekhi teri wafa sajna')
time.sleep(1)
print('Bhul gayi si mai raah sajna')
time.sleep(1)
print('Jandi jandi kho gayi saah')
time.sleep(1)
print('Khwaabaan de vich tere')
time.sleep(1)
print('Main taan hi uchiyan deewaran rakhiyan')
time.sleep(1)
print('Iss dil de chaar chufere')
time.sleep(1)
print('Naale saambh k rakhiya si')
time.sleep(1)
print('Koi dil ch na laa de dere')